### ISSUE TITLE
Will this replace the default bluetooth, mine seems to be defect

### ISSUE THREAD

**Issue by andershoejlund** [pwalther/iot-ha-ikea-enebyV1#1]
Hi Pwalther,

I cannot seem to connect or factory reset my eneby speaker, would your hack help me out?

Thanks, best regards Anders

**Comment by pwalther** [comment]
Hi Anders, unfortunately I think this will not help you, it still requires a bluetooth connection in the end. You could open the box to check if maybe there is a physical connection problem?
