### ISSUE TITLE
EnebyV2 compatibility

### ISSUE THREAD

**Issue by BasVanBoven** [pwalther/iot-ha-ikea-enebyV1#2]
Hej! Thanks a lot for sharing this repository, really useful! Bit of an open question here I guess, but I am willing to purchase an EnebyV2 and test if this hack still works. Before I unnecessarily take the plunge and additionally void the warranty: is there anything known about V2 compatibility at this moment in time (also considering the repo name)? There is always the chance of a board swap of course, but I cannot seem to find any teardowns that make this seem likely.

**Comment by pwalther** [comment]
Bit of a late reply. As long as they use the same kind of volume knob, it should work. I'd also check this out:
https://www.espruino.com/Ikea+Eneby+Speaker+Controller
