### ISSUE TITLE
Error with mycredentials.h

### ISSUE THREAD

**Issue by fesamper** [pwalther/iot-ha-ikea-enebyV1#3]
Hi,
Thanks for sharing your work.
This is the first time I work with platformio. When I import your project and I try to build I have an error:
src\main.cpp:6:10: fatal error: mycredentials.h: No such file or directory

I understand project needs a file called mycredentials.h that I need to create but I don't know what I have to put inside.
Can you please tell me structure and information content for this file?
In the main.cpp I changed ssid, password and mqtt_server ip but I think is missing mqtt_user and password (maybe this information needs to be in the mycredentials.h)
Thanks,

**Comment by pwalther** [comment]
Don't have the source / setup with me right now, but:
In the platformio.ini, I think you can use something like this:

```
lib_extra_dirs = 
    /Users/jcbsk/OneDrive/Documents/Github/Atmega328p_Addons/
```

https://community.platformio.org/t/including-headers-and-src-from-other-directories-with-pio/12341
